---
title: "Lab 3"
author: "CJ"
format: html
editor: visual
---

## 1. **Read in the data**

```{r}
library(dplyr)
library(data.table)
library(dtplyr)
library(readr)
library(leaflet)
library(lubridate)

download.file(
  "https://raw.githubusercontent.com/USCbiostats/data-science-data/master/02_met/met_all.gz",
  destfile = file.path("~", "Downloads", "met_all.gz"),
  method   = "libcurl",
  timeout  = 60
)

met <- fread(file.path("~", "Downloads", "met_all.gz"))

```

## 2

```{r}
dim(met)
head(met)
tail(met)
```

## 3

```{r}
str(met)
```

## 4

```{r}
table(met$year)
table(met$day)
table(met$hour)
summary(met$temp)
met[met$temp == -40.00] <- NA
met <- met[temp > -15]
met2 <- met[order(temp, decreasing = FALSE)]
head(met2)
summary(met$elev)
met[met$elev == 9999.0] <- NA
summary(met$wind.sp)

```

## 5

```{r}
met <- met[temp > -15]
met2 <- met[order(temp, decreasing = FALSE)]
```

## 6

```{r}
elev <- met[elev==max(elev), list(temp, wind.sp)]
summary(elev)
cor(elev$temp, elev$wind.sp, use="complete")

```

## 7

```{r}
hist(met$wind.sp, breaks = 100)
hist(met$temp)
hist(met$wind.sp)


```
